Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x37c4ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x37c4a50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x37cf110>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x37cf6d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x37cfd90>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/
Requirement already up-to-date: pip in /apps/tools/pip/usr/lib/python2.7/site-packages (10.0.1)
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
now install numpy
Collecting numpy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x2372650>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/numpy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x2372a50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/numpy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x2379110>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/numpy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x23796d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/numpy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x2379d90>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/numpy/
  Could not find a version that satisfies the requirement numpy (from versions: )
No matching distribution found for numpy
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
now load TF
Traceback (most recent call last):
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: /apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/machine-learning/tensorflow/1.11/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/apps/machine-learning/tensorflow/1.11/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/nfshome/store04/users/c.c0919382/fyp_scw1427/genetic_augment/evaluator/evaluate_policies.py", line 27, in <module>
    import evaluator.custom_ops as ops
  File "/nfshome/store04/users/c.c0919382/fyp_scw1427/genetic_augment/evaluator/custom_ops.py", line 26, in <module>
    import numpy as np
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /apps/languages/python-numpy/1.14.5/el7/usr/lib64/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

